<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXeVtr5U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXeVtr5U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXeVtr5U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXeVtr5U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXeVtr5U\App_KernelDevDebugContainer([
    'container.build_hash' => 'XeVtr5U',
    'container.build_id' => '1780635e',
    'container.build_time' => 1596114803,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXeVtr5U');
