<?php

namespace ContainerXeVtr5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tv08cadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tv08cad' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tv08cad'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PhotosController::delete' => ['privates', '.service_locator.P5p.8.v', 'get_ServiceLocator_P5p_8_VService', true],
            'App\\Controller\\PhotosController::edit' => ['privates', '.service_locator.P5p.8.v', 'get_ServiceLocator_P5p_8_VService', true],
            'App\\Controller\\PhotosController::index' => ['privates', '.service_locator.dCIico_', 'get_ServiceLocator_DCIicoService', true],
            'App\\Controller\\PhotosController::show' => ['privates', '.service_locator.P5p.8.v', 'get_ServiceLocator_P5p_8_VService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\PhotosController:delete' => ['privates', '.service_locator.P5p.8.v', 'get_ServiceLocator_P5p_8_VService', true],
            'App\\Controller\\PhotosController:edit' => ['privates', '.service_locator.P5p.8.v', 'get_ServiceLocator_P5p_8_VService', true],
            'App\\Controller\\PhotosController:index' => ['privates', '.service_locator.dCIico_', 'get_ServiceLocator_DCIicoService', true],
            'App\\Controller\\PhotosController:show' => ['privates', '.service_locator.P5p.8.v', 'get_ServiceLocator_P5p_8_VService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\PhotosController::delete' => '?',
            'App\\Controller\\PhotosController::edit' => '?',
            'App\\Controller\\PhotosController::index' => '?',
            'App\\Controller\\PhotosController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PhotosController:delete' => '?',
            'App\\Controller\\PhotosController:edit' => '?',
            'App\\Controller\\PhotosController:index' => '?',
            'App\\Controller\\PhotosController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
