<?php

namespace ContainerXeVtr5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.P5p.8.v.App\Entity\Photos' shared service.
     *
     * @return \App\Entity\Photos
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.P5p.8.v": it references class "App\\Entity\\Photos" but no such service exists.');
    }
}
